# This file was automatically generated by SWIG
package Replication::Recall::Client;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package Replication::Recall::Client;
bootstrap Replication::Recall::Client;
var_Client_init();
@EXPORT = qw( );
1;
