# This file was automatically generated by SWIG
package Replication::Recall::Server;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package Replication::Recall::Server;
bootstrap Replication::Recall::Server;
var_Server_init();
@EXPORT = qw( );
1;
